source 'https://github.com/CocoaPods/Specs.git'
#plugin 'slather'

platform :ios, '7.0'
#inhibit_all_warnings!

target 'Example' do
  pod 'CocoaUPnP', :path => '../CocoaUPnP.podspec'
end

target 'ExampleTests' do
  pod 'Specta', '~> 1'
  pod 'Expecta', '~> 1'
  pod 'OCMock', '~> 3'
  pod 'OHHTTPStubs', '~> 4'
end

