source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Example' do
  pod 'CocoaUPnP', :path => '../CocoaUPnP.podspec'
end

target 'ExampleTests' do
  pod 'Specta', '~> 1.0.7'
  pod 'Expecta', '~> 1.0.6'
  pod 'OCMock', '~> 3.4.3'
  pod 'OHHTTPStubs', '~> 6.1.0'
end

# Xcode 10 generates a bunch of warnings when using CocoaPods
# when the deployment target of pods is set to lower than the
# project deployment target.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

