source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'Example' do
  pod 'CocoaUPnP', :path => '../CocoaUPnP.podspec'
end

target 'ExampleTests' do
  pod 'Specta', '~> 1'
  pod 'Expecta', '~> 1'
  pod 'OCMock', '~> 3'
  pod 'OHHTTPStubs', '~> 4'
end

